# Generated by Django 4.0.dev20210216092534 on 2021-03-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Name',
            field=models.TextField(max_length=100),
        ),
    ]
