# Generated by Django 4.0.dev20210216092534 on 2021-03-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_posts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Name',
            field=models.TextField(blank=True),
        ),
    ]
