# Generated by Django 4.0.dev20210216092534 on 2021-03-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
