# Generated by Django 3.1.7 on 2021-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_posts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField(blank=True)),
                ('requester_name', models.TextField(blank=True)),
                ('book_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
