# Generated by Django 3.1.7 on 2021-03-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210314_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_collection',
            name='book_name',
            field=models.TextField(blank=True),
        ),
    ]
