# Generated by Django 4.0.dev20210216092534 on 2021-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Title',
            field=models.TextField(blank=True),
        ),
    ]
