# Generated by Django 3.1.7 on 2021-03-14 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210314_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collection',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cars'),
            preserve_default=False,
        ),
    ]
