# Generated by Django 3.1.7 on 2021-03-15 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_user_collection_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_collection',
            old_name='book_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='photo',
        ),
        migrations.AddField(
            model_name='user_collection',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
