# Generated by Django 4.0.dev20210216092534 on 2021-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210313_2248'),
        ('books', '0009_auto_20210315_1052'),
    ]

    operations = [
    ]
