# Generated by Django 4.0.dev20210216092534 on 2021-03-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_horror_mystery_romantic_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horror',
            name='descritption',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='descritption',
        ),
        migrations.RemoveField(
            model_name='romantic',
            name='descritption',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='descritption',
        ),
    ]
