# Generated by Django 4.0.dev20210216092534 on 2021-03-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210328_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_collection',
        ),
    ]
