# Generated by Django 4.0.dev20210216092534 on 2021-03-29 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0014_alter_user_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_collection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_collection1', to=settings.AUTH_USER_MODEL),
        ),
    ]
